import type { CatalogEntry } from "@/lib/clubFitting/types";

/**
 * Illustrative models only — not an endorsement or live inventory.
 * Tags drive matching from fitting rules.
 */
export const FITTING_CATALOG: CatalogEntry[] = [
  {
    id: "tm-qi10",
    brand: "TaylorMade",
    model: "Qi10",
    category: "driver",
    tags: ["regular", "stiff", "neutral", "mid-launch", "mid-spin", "midweight"],
    blurb: "Forgiving driver platform with stable mid-launch for everyday speed bands.",
  },
  {
    id: "tm-qi10-max",
    brand: "TaylorMade",
    model: "Qi10 Max",
    category: "driver",
    tags: ["senior", "regular", "draw-biased", "high-launch", "mid-spin", "lightweight"],
    blurb: "Higher MOI / draw-leaning option when misses leak right or launch needs help.",
  },
  {
    id: "callaway-paradise",
    brand: "Callaway",
    model: "Paradym Ai Smoke Max",
    category: "driver",
    tags: ["regular", "stiff", "draw-biased", "high-launch", "mid-spin", "midweight"],
    blurb: "Easy launch with draw bias for players who leave face open.",
  },
  {
    id: "titleist-gt2",
    brand: "Titleist",
    model: "GT2",
    category: "driver",
    tags: ["stiff", "x-stiff", "neutral", "mid-launch", "mid-spin", "midweight", "heavy"],
    blurb: "Tour-inspired mid-launch head for firmer shafts and cleaner paths.",
  },
  {
    id: "titleist-gt3",
    brand: "Titleist",
    model: "GT3",
    category: "driver",
    tags: ["stiff", "x-stiff", "fade-biased", "mid-launch", "low-spin", "heavy"],
    blurb: "Lower-spin / workable profile when spin is high or you prefer less draw help.",
  },
  {
    id: "ping-g430-max",
    brand: "Ping",
    model: "G430 Max",
    category: "driver",
    tags: ["senior", "regular", "stiff", "neutral", "high-launch", "mid-spin", "lightweight"],
    blurb: "High-MOI max head for slower-to-mid speeds needing forgiveness.",
  },
  {
    id: "cobra-darkspeed-ls",
    brand: "Cobra",
    model: "Darkspeed LS",
    category: "driver",
    tags: ["stiff", "x-stiff", "fade-biased", "mid-launch", "low-spin", "heavy"],
    blurb: "Low-spin LS shape for faster swingers who balloon or spin up.",
  },
  {
    id: "ping-g430",
    brand: "Ping",
    model: "G430",
    category: "iron",
    tags: ["senior", "regular", "game-improvement", "high-launch", "lightweight", "midweight"],
    blurb: "Game-improvement cavity that launches easily for moderate speeds.",
  },
  {
    id: "tm-p790",
    brand: "TaylorMade",
    model: "P790",
    category: "iron",
    tags: ["regular", "stiff", "players-distance", "mid-launch", "midweight"],
    blurb: "Players-distance hollow body — speed with a cleaner look.",
  },
  {
    id: "titleist-t100",
    brand: "Titleist",
    model: "T100",
    category: "iron",
    tags: ["stiff", "x-stiff", "players", "mid-launch", "mid-spin", "heavy"],
    blurb: "Players cavity for better ball-strikers who want feedback and control.",
  },
  {
    id: "mizuno-jpz919",
    brand: "Mizuno",
    model: "JPX 923 Hot Metal",
    category: "iron",
    tags: ["regular", "stiff", "game-improvement", "high-launch", "midweight"],
    blurb: "Hot Metal forgiveness with a mid-high launch profile.",
  },
  {
    id: "callaway-apex-ai",
    brand: "Callaway",
    model: "Apex Ai200",
    category: "iron",
    tags: ["stiff", "players-distance", "mid-launch", "mid-spin", "midweight"],
    blurb: "Players-distance look with help on miss-hits.",
  },
  {
    id: "vokey-sm10",
    brand: "Titleist",
    model: "Vokey SM10",
    category: "wedge",
    tags: ["mid-spin", "regular", "stiff", "neutral"],
    blurb: "Tour-standard grind family — match bounce to turf, not just loft.",
  },
  {
    id: "cleveland-rtx6",
    brand: "Cleveland",
    model: "RTX 6 ZipCore",
    category: "wedge",
    tags: ["mid-spin", "high-launch", "regular", "stiff", "game-improvement"],
    blurb: "Forgiving ZipCore face for players who want spin without a blade grind.",
  },
  {
    id: "shaft-ventus-blue",
    brand: "Fujikura",
    model: "Ventus Blue",
    category: "shaft",
    tags: ["stiff", "x-stiff", "mid-launch", "mid-spin", "midweight", "heavy"],
    blurb: "Stable mid-launch wood shaft often fit to firmer swings.",
  },
  {
    id: "shaft-ventus-red",
    brand: "Fujikura",
    model: "Ventus Red",
    category: "shaft",
    tags: ["senior", "regular", "high-launch", "lightweight", "midweight"],
    blurb: "Higher-launch wood profile for players who need help getting the ball up.",
  },
  {
    id: "shaft-tensei-1k",
    brand: "Mitsubishi",
    model: "TENSEI 1K Black",
    category: "shaft",
    tags: ["stiff", "x-stiff", "low-spin", "mid-launch", "heavy"],
    blurb: "Lower-spin counter for fast swingers who overspin the driver.",
  },
  {
    id: "shaft-project-x",
    brand: "Project X",
    model: "LZ / IO (iron)",
    category: "shaft",
    tags: ["stiff", "x-stiff", "players", "players-distance", "mid-spin", "heavy"],
    blurb: "Firmer iron shafts for stronger transitions and higher speeds.",
  },
  {
    id: "shaft-kbs-tour",
    brand: "KBS",
    model: "Tour",
    category: "shaft",
    tags: ["regular", "stiff", "players", "mid-launch", "midweight"],
    blurb: "Classic mid-weight iron shaft for a wide regular/stiff audience.",
  },
  {
    id: "shaft-recoil",
    brand: "UST Mamiya",
    model: "Recoil",
    category: "shaft",
    tags: ["senior", "regular", "game-improvement", "high-launch", "lightweight"],
    blurb: "Graphite iron option when you want lighter weight and easier launch.",
  },
];
